### ISSUE TITLE
SubscriptionTerm is missing termUnit property

### ISSUE THREAD

**Issue by Tomanow** [microsoft/commercial-marketplace-client-java#35]
**Describe the bug**
Missing property used by the marketplace APIs.

**To Reproduce**

- `SubscriptionTerm` is missing `termUnit` of type `TermUnitEnum` (which exists in models).

**Expected behavior**
- `SubscriptionTerm` contains `termUnit` property of type `TermUnitEnum`.
- Getter and setter methods exist for `SubscriptionTerm.termUnit` property.

**Comment by santhoshb-msft** [comment]
Thank you @Tomanow 
Fixed pas part of #36
